@startuml
start

:Пользователь выбирает действие;

if (GET список?) then
  --> :GET /api/users?page=...
elseif (GET user?) then
  --> :GET /api/users/{id}
elseif (POST?) then
  --> :POST /api/users
elseif (PUT/PATCH?) then
  --> :PUT или PATCH /api/users/{id}
elseif (DELETE?) then
  --> :DELETE /api/users/{id}
else
  --> :Ошибка выбора действия
endif

stop
@enduml
