@startuml
actor User
participant Reqres_API
database Reqres_DB

User -> Reqres_API: DELETE /api/users/{id}

opt Отсутствует API-ключ
    Reqres_API --> User: 403 Forbidden
else Ключ передан
    alt User не найден
        Reqres_API --> User: 404 User not found
    else Пользователь найден
        Reqres_API -> Reqres_DB: DELETE FROM users WHERE id = {id}
        Reqres_DB --> Reqres_API: OK
        Reqres_API --> User: 204 No Content
    end
end
@enduml
